defaults:
  - base

# Override agent_proxy settings to enable parallel rollout
agent_proxy:
  max_turn: 5
  action_sep: "||"
  max_actions_per_turn: 5
  use_turn_scores: False
  enable_think: True
  use_parallel_rollout: True # Enable joblib-based parallel environment rollout
  parallel_n_jobs: 4 # Number of parallel workers for environment rollout
  reward_normalization:
    grouping: "state"
    method: "identity"

# You might want to adjust these for better parallel performance
trainer:
  project_name: ragen_parallel
  experiment_name: parallel_test
  total_training_steps: 200
  validation_steps: 1
  val_before_train: True
  n_gpus_per_node: 2
  test_freq: 10
  save_freq: 50
  generations_to_log_to_wandb: 
    train: 128
    val: 20
  logger: [ 'console', 'wandb' ]